name: CI

on:

  workflow_dispatch:


jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: clone
        run: |
          git clone https://github.com/kiecok/test.git
          cd test
          rm -rf whgle/*
          rm -rf whgle/.??*
          git rm -r -f --cached whgle/* 
          #git clone https://github.com/benbusby/whoogle-search.git whgle
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/kiecok/test.git --force

  sync:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: clone
        run: |
          git clone https://github.com/kiecok/test.git
          cd test
          git clone https://github.com/benbusby/whoogle-search.git whgle
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "$(date "+%Y%m%d-%H%M")"
          git push https://${GITHUB_ACTOR}:${{ secrets.PAT }}@github.com/kiecok/test.git --force

